src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le titre du projet est obligatoire")]
    #[Assert\Length(min: 3, max: 255, minMessage: "Le titre du projet doit avoir au moins 3 caractères", maxMessage: "Le titre du projet doit avoir au maximum 255 caractères")]
    private ?string $title = null;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'projects')]
    private Collection $users;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Assert\NotBlank(message: "La date de création du projet est obligatoire")]
    private ?\DateTimeInterface $creation_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message: "La description du projet est obligatoire")]
    private ?string $description = null;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Task::class)]
    private Collection $tasks;

    #[ORM\ManyToOne]
    private ?User $creator = null;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Invitation::class)]
    private Collection $invitations;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->tasks = new ArrayCollection();
        $this->invitations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addProject($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removeProject($this);
        }

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(?\DateTimeInterface $creation_date): static
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Task>
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): static
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks->add($task);
            $task->setProject($this);
        }

        return $this;
    }

    public function removeTask(Task $task): static
    {
        if ($this->tasks->removeElement($task)) {
            // set the owning side to null (unless already changed)
            if ($task->getProject() === $this) {
                $task->setProject(null);
            }
        }

        return $this;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): static
    {
        $this->creator = $creator;

        return $this;
    }

    /**
     * @return Collection<int, Invitation>
     */
    public function getInvitations(): Collection
    {
        return $this->invitations;
    }

    public function addInvitation(Invitation $invitation): static
    {
        if (!$this->invitations->contains($invitation)) {
            $this->invitations->add($invitation);
            $invitation->setProject($this);
        }

        return $this;
    }

    public function removeInvitation(Invitation $invitation): static
    {
        if ($this->invitations->removeElement($invitation)) {
            // set the owning side to null (unless already changed)
            if ($invitation->getProject() === $this) {
                $invitation->setProject(null);
            }
        }

        return $this;
    }
}

src/Entity/Task.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\TaskRepository;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TaskRepository::class)]
class Task
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message : "Le titre de la tache est obligatoire")]
    #[Assert\Length(min: 3, max: 255, minMessage: "Le titre de la tache doit avoir au moins 3 caractères", maxMessage: "Le titre de la tache doit avoir au maximum 255 caractères")]

    private ?string $title = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "La description de la tache est obligatoire")]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "La priorité de la tache est obligatoire")]

    private ?string $priority = null;

    #[ORM\Column(type: "datetime")]
    #[Assert\NotBlank(message: "La date de création de la tache est obligatoire")]
    private $creation_date = null;

    #[ORM\Column(type: "datetime")]
    #[Assert\NotBlank(message: "La date de rendu de la tache est obligatoire")]
    #[Assert\GreaterThanOrEqual(
         propertyPath: "creation_date",
         message: "La date de rendu de la tache doit être postérieure ou égale à la date de création de la tache."
    )]
    private $due_date = null;

    #[ORM\ManyToOne(inversedBy: 'tasks')]
    private ?User $owner = null;

    #[ORM\ManyToOne(inversedBy: 'tasks')]
    private ?Project $project = null;

    #[ORM\Column(nullable: true)]
    private ?bool $finished = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPriority(): ?string
    {
        return $this->priority;
    }

    public function setPriority(?string $priority): static
    {
        $this->priority = $priority;

        return $this;
    }

    public function getCreationDate(): ?\DateTime
    {
        return $this->creation_date;
    }

    public function setCreationDate(?\DateTime $creation_date): static
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getDueDate(): \DateTime
    {
        return $this->due_date;
    }

    public function setDueDate(?\DateTime $due_date): static
    {
        $this->due_date = $due_date;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): static
    {
        $this->owner = $owner;

        return $this;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): static
    {
        $this->project = $project;

        return $this;
    }

    public function isFinished(): ?bool
    {
        return $this->finished;
    }

    public function setFinished(?bool $finished): static
    {
        $this->finished = $finished;

        return $this;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType as TypeTextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TypeTextType::class, [
                'label' => 'Titre',
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Invitation;
use DateTime;
use App\Entity\User;
use App\Entity\Project;
use App\Form\InvitationType;
use App\Form\ProjectInvitationType;
use App\Form\ProjectType;
use App\Repository\InvitationRepository;
use App\Repository\UserRepository;
use App\Repository\ProjectRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Validator\Constraints\Date;

class ProjectController extends AbstractController
{
    /**
     * @Route("project/{user_id}", name="project", priority=-1)
     */
    public function showAll($user_id, UserRepository $userRepository): Response
    {
        /**
         * @var User $user
         */
        // On récupère l'utilisateur connecté
        $loggedUser = $this->getUser();

        if (!$loggedUser) {
            throw $this->createAccessDeniedException("Veuillez vous connecter pour pouvoir voir vos projets");
        }

        // On cherche l'utilisateur avec l'id passé dans l'url
        $user = $userRepository->find($user_id);

        // Si l'utilisateur connecté et l'utilisateur passé dans l'url sont les memes
        if ($loggedUser === $user) {
            // On récupère ses projets créés
            $userProjectsQuery = $userRepository->findUserWithProjects($user->getId());
            $userProjects = $userProjectsQuery->getProjects();

            // Conversion sous forme d'array
            $projects = $userProjects->toArray();

            return $this->render('project/index.html.twig', [
                'projects' => $projects,
            ]);
        } else {
            throw $this->createAccessDeniedException("Vous n'êtes pas l'utilisateur recherché");
        }


        return $this->render('project/index.html.twig', [
            // 'projects' => $projects,
        ]);
    }

    /**
     * @Route("/project/create", name="project_create")
     */
    public function create(Request $request, EntityManagerInterface $em): Response
    {
        $project = new Project;

        $today = new DateTime();
        $project->setCreationDate($today);

        $user = $this->getUser();
        if (!$user) {
            throw $this->createAccessDeniedException("Veuillez vous connecter");
        }


        $form = $this->createForm(ProjectType::class, $project);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $project->addUser($user);
            $project->setCreator($user);
            $em->persist($project);
            $em->flush();

            return $this->redirectToRoute('project_show', [
                'id' => $project->getId(),
                'project_id' => $project->getId()
            ]);
        }

        return $this->render('project/create.html.twig', [
            'formView' => $form->createView()
        ]);
    }

    /**
     * @Route("/project/{project_id}/show", name="project_show")
     */
    public function show($project_id, ProjectRepository $projectRepository, Request $request, UserRepository $userRepository, EntityManagerInterface $em, InvitationRepository $invitationRepository): Response
    {
        $project = $projectRepository->find($project_id);
        $user = $this->getUser();

        $formInvitation = $this->createForm(InvitationType::class);

        if (!$project) {
            throw $this->createNotFoundException("Le projet n'a pas été trouvé");
        }

        $contributors = ($project->getUsers()->toArray());
        $contributorsEmail = [];
        foreach ($contributors as $contributor) {
            $contributorsEmail[] = $contributor->getEmail();
        }

        $formInvitation->handleRequest($request);

        if ($formInvitation->isSubmitted() && $formInvitation->isValid()) {
            if ($user === $project->getCreator()) {
                $recipient = $request->request->get('invitation')['email'];
                $recipient = $userRepository->findOneBy(['email' => $recipient]);

                // dd($invitationRepository->findOneBy(['recipient' => $recipient]), in_array($recipient, $contributorsEmail) );
                // On vérifie si l'utilisateur a déjà été invité ou s'il fait déjà partie du projet
                if ($invitationRepository->findOneBy(['recipient' => $recipient]) || in_array($recipient->getEmail(), $contributorsEmail)) {
                    throw $this->createAccessDeniedException("L'utilisateur entré fait déjà partie du projet ou a déjà été invité");
                } else {
                    $invitation = new Invitation;
                    $invitation->setSender($user)
                        ->setRecipient($recipient)
                        ->setProject($project)
                        ->setStatus("En attente")
                        ->setCreationDate(new DateTime());

                    $em->persist($invitation);
                    $em->flush();

                    return $this->render('project/show.html.twig', [
                        'project' => $project,
                        'contributors' => $contributors,
                        'formView' => $formInvitation->createView(),
                        'projectInvitation' => $project->getInvitations()->toArray()
                    ]);
                }
            } else {
                throw $this->createAccessDeniedException("Vous n'êtes pas le créateur de la tache");
            }
        }



        if ($formInvitation->isSubmitted() && $formInvitation->isValid()) {
        }

        return $this->render('project/show.html.twig', [
            'project' => $project,
            'contributors' => $contributors,
            'formView' => $formInvitation->createView()
        ]);
    }
}

templates/project/create.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Créer un nouveau projet
{% endblock %}

{% block body %}
	{{ form_start(formView) }}
	{{ form_errors(formView) }}
	{{ form_widget(formView) }}

	<button type="submit" class="btn btn-primary p-2 my-3">Créer le projet</button>

	{{ form_end(formView) }}
{% endblock %}

templates/project/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vos projets
{% endblock %}

{% block body %}

	{% if app.user %}


		<div class="row justify-content-center align-items-center mb-3">
			<a href="{{ path('project_create') }}" class="btn btn-primary btn-lg w-75 d-flex align-items-center justify-content-center">
				<ion-icon name="add-outline" class="pt-1"></ion-icon>
				Créer un nouveau projet</a>
		</div>

		<div class="row text-center my-3">
			<h2>Vos projets</h2>
		</div>
		<div class="row my-3">
			{% for project in projects|sort((a,b) => a.creationDate <=> b.creationDate) %}
				<div class="col-md-4 mb-3">
					<div class="card h-100 d-flex flex-column m-3">
						<div class="card-body">
							<h5 class="card-title">{{ project.title }}</h5>
							<p class="card-text">{{ project.description }}</p>
						</div>
						<div class="mt-auto card-footer">
							<small class="text-muted">Crée le
								{{ project.creationDate | date('Y-m-d H:i:s') }}</small>
						</div>
						<a href="{{ path('project_show', {project_id: project.getId}) }}" class="stretched-link text-decoration-none"></a>
					</div>
				</div>
			{% endfor %}
		</div>


	{% endif %}
{% endblock %}

templates/project/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
	{{ project.title }}
{% endblock %}

{% block body %}
	<div class="row">
		<div class="col">
			<h2 class="text-decoration-underline">{{ project.title }}</h2>
		</div>
	</div>
	<div class="row">
		<h4 class="text-center m-3">Les contributeurs</h4>

		<table class="table">
			<thead>
				<tr>
					<th>Nom complet</th>
					<th>Email</th>
					<th>Statut</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				{% for contributor in contributors %}
					<tr>
						<td>{{ contributor.fullName }}</td>
						<td>{{ contributor.email }}</td>
						<td>
							{% if project.creator.id == contributor.id %}
								<span class="badge bg-success">Chef</span>
							{% else %}
								<span class="badge bg-primary">Membre</span>
							{% endif %}
						</td>
						{% if app.user != contributor %}
							<td>
								<a class="btn btn-primary" data-user-id="{{ contributor.id }}" href="{{ path('message_show', {user1: app.user.id, user2: contributor.id}) }}">Envoyer un message</a>
							</td>
						{% endif %}
					</tr>
				{% endfor %}
			</tbody>
		</table>
		<div>
			<h4 class="text-center m-3">Ajouter un utilisateur au projet</h4>

			{{ form_start(formView) }}
			<div class="row justify-content-center">
				<div class="col-md-4">
					<div class="input-group">
						{{ form_errors(formView.email) }}
						{{ form_label(formView.email, null, {'label_attr': {'style': 'display: none;'}}) }}
						{{ form_widget(formView.email, {'attr': {'class': 'form-control', 'placeholder': 'Adresse e-mail'}}) }}
						<div class="input-group-append">
							{{ form_row(formView.send, {'attr': {'class': 'btn bg-primary text-white mx-2'}}) }}
						</div>
					</div>
				</div>
			</div>
			{{ form_end(formView) }}
		</div>

	</div>
</div>
{% if project.tasks|length > 0 %}
	<div class="row my-3">
		{% for task in project.tasks|sort((a, b) => a.creationDate <=> b.creationDate) %}
			<div class="col-md-4 my-3">
				<div class="card h-100 position-relative">
					<span class="badge bg-{{task.finished ? 'success' : 'warning'}} rounded-pill position-absolute top-0 end-0 m-2">{{task.finished ? 'Terminé' : 'En cours'}}</span>
					<div class="card-body d-flex flex-column justify-content-between m-3">
						<h5 class="card-title text-center">{{ task.title }}</h5>
						<p class="card-text text-center">{{ task.description }}</p>
						<p class="card-text text-center">Priorité :
							{{ task.priority }}</p>
						<p class="card-text text-center">Date de création :
							{{ task.creationDate|date('Y-m-d') }}</p>
						<p class="card-text text-center" onclick="confirm('Etes vous sur de supprimer cette tache ?')">Date d'échéance :
							{{ task.dueDate|date('Y-m-d') }}</p>
						<div class="d-flex justify-content-between align-items-center">
							{% if project.creator.id == app.user.id %}
								<a href="{{ path('task_edit', {project_id: project.id, task_id: task.id})}}" class="btn btn-warning my-1">Modifier</a>
								<a href="{{ path('task_finished', {project_id: project.id, task_id: task.id}) }}" class="btn btn-{{task.finished ? 'dark' : 'success' }} my-1">{{ task.finished ? 'Annuler' : 'Terminer'}}</a>
								<a href="{{ path('task_delete', {project_id: project.id, task_id: task.id}) }}" class="btn btn-danger my-1" onclick="return confirmAction(event, 'Êtes-vous sûr de vouloir supprimer cette tâche ?')">Supprimer</a>
							{% endif %}
						</div>

					</div>
				</div>
			</div>
		{% endfor %}
	</div>
{% else %}
	<p>Aucune tache n'a été créée pour ce projet</p>
{% endif %}
{% if project.creator.id == app.user.id %}
	<div class="row justify-content-center align-items-center mb-3">
		<a href="{{ path('task_create', {project_id: project.id}) }}" class="btn btn-primary d-flex align-items-center justify-content-center">
			<ion-icon name="add-outline" class="pt-1"></ion-icon>
			Créer une nouvelle tache</a>
	</div>
{% endif %}{% endblock %}